version: "3"
services:
  ubersnap:
    container_name: ubersnap
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public-static:/app/public-static
      - ./config.yml:/app/config.yml
    ports:
      - 8000:8000
    restart: unless-stopped
